name: Python package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build
        run: poetry version ${{ github.ref_name }} && poetry build
      - name: pypi config
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - name: pypi publish
        run: poetry publish